version: '3.1'
services:
  stats-server:
    container_name: "stats"
    build: stats/stats-server
    image: stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: "stats"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  ewm-service:
    container_name: "ewm_service_container"
    image: ewm-service
    build: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5431/ewm
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  ewm-db:
    image: postgres:14-alpine
    container_name: "ewm_db_container"
    ports:
      - "5431:5431"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ewm"

